### PR TITLE
Added Bambu Lab PETG-HF

### PR DESCRIPTION
**Pull request by L0rdS474n**
Just added Bambu Lab PETG-HF

### CODE REVIEW

**Comment by L0rdS474n** [comment]
Not sure why it complain about this rule, I followed PAHT-CF when I created PETG-HF

**Comment by Donkie** [comment]
The -CF ending was meant to indicate additives, either carbon fiber (CF) or glass fiber (GF)

HF is not an additive so it's technically wrong to write it in the same format.

Maybe @StuSerious can give input here?

**Comment by L0rdS474n** [comment]
> The -CF ending was meant to indicate additives, either carbon fiber (CF) or glass fiber (GF)
> 
> HF is not an additive so it's technically wrong to write it in the same format.
> 
> Maybe @StuSerious can give input here?

Yes, it just indicate high flow, PETG+HF sounds wrong too. They name it as PETG HF on the site so that's the last commit I did.
And TPU for AMS, how should we name that?

**Comment by Donkie** [comment]
TBH I think "PETG" alone is good enough for the material field here, then you can perhaps put HF somewhere in the name field.

**Pull request merged**
