### PR TITLE
materials: add technopolymers

### PR DESCRIPTION
**Pull request by StuSerious**
This adds some 3D printable high-end polymers and their densities, that were not yet added to the materials.json file.
I will add more once I go through more of my inventory.

The rationale behind 022fb6383788e4e4f883cc30060d3444bbca2243 is that by largely adopted convention the names of the polymers are written first, than their commercial/everyday name.
While I like it better like this, 022fb6383788e4e4f883cc30060d3444bbca2243 can be easily reverted if you don't agree.

### CODE REVIEW

**Comment by Donkie** [comment]
Maybe material field should be a list of strings instead of having some formatting here, would make it more flexible. Alternatively have two fields, a "scientific name" and a "friendly name". What do you think?

**Comment by StuSerious** [comment]
This kind of ties in with https://github.com/Donkie/SpoolmanDB/issues/5, so with a bit of guidance I could 

With a list of strings, we could set it by convention that the material acronym comes first, and then the commercial name (e.g. `[PMMA, Plexiglas]`) but that would make the schema convoluted.

Overall, I'm in favor of adding an additional key so that there can be a specific name. I would suggest `material-acronym` and `material-name`.

Feedback welcome!

**Comment by Donkie** [comment]
It's a bit difficult because I think it's important to capture what name people are most familiar with. You always talk about PLA and not Polylactic acid for example, so there the acronym is the common name. But with Nylon for example you always talk about Nylon and not PA.

That's why I'm thinking it's good to have a list of strings for the names, and then have the common name be the first string, and the remaining strings are alternative names.

What do you think?

**Comment by StuSerious** [comment]
Completely agree, wouldn't want to confuse people..

I guess the system as is right now is good enough, I mean front-ends can just regex the acronym if they want, plus most are going to get it from the filaments themselves, not the materials.

I'll drop 022fb6383788e4e4f883cc30060d3444bbca2243 for now, it will be easy to update if we go for a list.

**Pull request merged**
